"""empty message

Revision ID: d570074d7db9
Revises: 
Create Date: 2024-03-21 15:41:57.021133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd570074d7db9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=True))
        batch_op.drop_column('type')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('answer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        #batch_op.alter_column('category',
        #       existing_type=sa.INTEGER(),
        #       type_=sa.String(),
        #       existing_nullable=True)
        batch_op.drop_constraint('category', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_foreign_key('category', 'categories', ['category'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.alter_column('category',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('answer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
