"""empty message

Revision ID: 4a094d707ef7
Revises: 1194b82e0c97
Create Date: 2023-09-14 08:55:51.420205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a094d707ef7'
down_revision = '1194b82e0c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos','completed', existing_type=sa.BOOLEAN())
    op.alter_column('todos','completed', nullable=True)
    op.alter_column('todos','completed', server_default=str('False'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
