"""empty message

Revision ID: 690a65cfd335
Revises: 
Create Date: 2023-09-11 13:35:31.876108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690a65cfd335'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
