"""empty message

Revision ID: c26bdf71e377
Revises: 690a65cfd335
Create Date: 2023-09-11 15:25:31.289135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26bdf71e377'
down_revision = '690a65cfd335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('todos',sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    op.alter_column('todos','completed', nullable=False)

    #with op.batch_alter_table('todos', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
    #    batch_op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')




    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('todos', schema=None) as batch_op:
    #    batch_op.drop_column('completed')

    op.drop_column('todos','completed')

    # ### end Alembic commands ###
